AddDoorGroup("АЛЬЯНС", TEAM_OVERWATCH, TEAM_ALPHAOWC, TEAM_ALPHAOWS, TEAM_ADMG, TEAM_ZAMADMG, TEAM_OTASPHCR, TEAM_OTASPHPVT, TEAM_OTASPHCS, TEAM_OTASPHCPL,
TEAM_OTASPHSGT, TEAM_OTASPHSPSG, TEAM_OTASPHLT, TEAM_OTASPHSPLT, TEAM_OTASPHCPT,
TEAM_OTACMDASSASSIN, TEAM_OTACMDHEVIK, TEAM_OTACMDOVERLORD, TEAM_CMDSECTORIALGCS, TEAM_CMDDVLGEN, TEAM_CMDCOMMISSARPT, TEAM_ADGOVPPT,
TEAM_ADINSPECTORMJR, TEAM_ADSUPERVISORMJR, TEAM_ELITECMDPPT, TEAM_ELITEMJR, TEAM_ELITEGUARDMJR, 
TEAM_SDWARDENCPT, TEAM_SDCHASERSER, TEAM_SDCOMBATSER, TEAM_SDTECHNICALSER,
TEAM_SDEMUSER, TEAM_INSTRMJR, TEAM_INSTRCPT, TEAM_MPDLT, TEAM_MPDSER, TEAM_OPDRD, TEAM_INSTRCDT, TEAM_ADV)
AddDoorGroup("ГСР", TEAM_VORTSLAVE, TEAM_POWAR, TEAM_FELDSHER, TEAM_SBORSHIK, TEAM_DIRECTOR)
AddDoorGroup("Ребелы", TEAM_REBEL, TEAM_REBELVETERAN, TEAM_REBELMEDIC, TEAM_REBELENGI, TEAM_REBELSPY, TEAM_REBELSTRELOK, TEAM_REBELVORT, TEAM_REBELBOOM,
TEAM_REBELCMD, TEAM_REBELLEADER, TEAM_REBELOPER, TEAM_REBELSNIPER, TEAM_REBELHEAVY, TEAM_REBELLINC )
AddDoorGroup("Учёные (ИВЕНТ)", TEAM_OMEGA, TEAM_OMEGAHEAL, TEAM_OMEGAHEAD)
AddDoorGroup("CoA", TEAM_CINORA, TEAM_APOSTOL, TEAM_PREDVEST, TEAM_PRAPOR, TEAM_POCHLYSNIK, TEAM_ADEPT)